### ISSUE TITLE
How to add 3rd framework to application build by theos?

### ISSUE THREAD

**Issue by wugensan** [theos/theos#110]
Hello,
        I need to add a 3rd framework to my application build by theos, but I don't know where should it be placed in my project directory or somewhere else, and how to modify the Makefile.
        Any help will be gratitude!!!

**Comment by thiesdiggity** [comment]
Hi @wugensan, I'm having the same issue. Were you able to figure this out? Any feedback would be greatly appreciated. Thanks!

**Comment by kirb** [comment]
The merge of kirb/theos has added proper support for non-Apple frameworks. You can place them in the `lib` directory, and then reference them with `thing_EXTRA_FRAMEWORKS = Blah`.

**Comment by kevinzheng** [comment]
@kirb EXTRA_FRAMEWORKS works for compiling without errors, but doesn't work on the device, why?

**Comment by ipadkid358** [comment]
It compiles on your main computer, but not on your iOS device? Or it compiles, but crashes when the binary is run on the iOS device? Is the framework on the iOS device?

**Comment by kirb** [comment]
How does it not work? Provide as much detail as possible, including exact error output. You can run `make troubleshoot` to quickly upload Theos error output to Ghostbin. If it’s building fine but fails to load at runtime, check syslog (using macOS Console.app, or `oslog` from Cydia) for dyld error messages. Particularly, iOS 11 will refuse to load frameworks installed to /Library/Frameworks. If this is your own framework, you must move it to /usr/lib with `MyFramework_INSTALL_PATH = /usr/lib`.

This is an old issue thread — if you think you’ve found a bug in Theos, please create another issue. Otherwise, take a look at [our advice on getting help](https://github.com/theos/theos/wiki/Help).

**Comment by kevinzheng** [comment]
@kirb Thank you for your very great help. I don't know if should replay there. I use `ldid -S` to sign the third party framework , then put it  at `/System/Library/Framework`, this way works. But if I put the framework at `/Library/Framework` or `/usr/lib`, it says `image not found` in the syslog. My environment is `iOS 11.1.2` with `Electra`, why can't the framework in `/usr/lib` be loaded? Very appreciate your help!
