### ISSUE TITLE
Create releases to make Theos available in Package Managers (apt, brew, ...)

### ISSUE THREAD

**Issue by Miladiir** [theos/theos#111]
Theos is a pretty nice system and it is pretty easy to install.
To make this process even easier, for example for installation automation with dotfiles, cider and brew on a Mac, or simply a long list of apt-gets on Ubuntu/Debian, there is not much to do for you.
The community can create formulas/packages and submit them, however a prerequisit for that is that Theos adopts a versioning scheme.

Please do so and update the version in Github releases on major additions and fixes to make theos behave like a modern piece of unix software.

**Comment by crazyquark** [comment]
I am looking forward for this feature too :)

**Comment by coolstar** [comment]
Also on Windows we could have a package that can be used with Cygwin's installer.

**Comment by alucard0134** [comment]
@coolstar i don't remember if cygwin locks its file system from windows and only does read only or not

**Comment by kirb** [comment]
I've had a few attempts at making packages for Theos a few times, and there's some things that need a fair bit of working out first.

I attempted to take a stab at this with [this Homebrew formula](https://github.com/hbang/homebrew-repo/blob/master/theos.rb). I'm still not happy with it, because Homebrew has its update system and Theos has its update system. Homebrew expects a new version every time the software has an update, but Theos has no concept of releases at the moment. The latest commit to master is the latest version. APT, etc. also have the same problem.

DHowett previously had a Theos package on his Cydia repo, but it sometimes wasn't updated (ie, he forgot). I began working on an iOS package because people requested it, and I used version numbers like `1.0-1+47cbd45`, the `-1` incrementing every time the package is updated, because that was all I could think of that would make APT/dpkg see it as an update.

Theos is fairly tightly integrated with Git; the vendor/{include,lib} directories are submodules (lib isn't right now, but it [will be](https://github.com/theos/lib) as soon as Git LFS becomes available for iOS) and as a package you lose all the flexibility you get from a Git repo. (After writing that I realised there could be a package for each component which mostly solves the problem.)

Also, who owns the package contents? root, most commonly. I wouldn't want to sudo all the time to make changes inside the user {include,lib} directories. You could chown to yourself, but then updates will change ownership back.

I definitely want to find a solution, because Theos as a package on every platform would be really nice. Not just for Homebrew and Cydia, but also Debian/Ubuntu, Arch, Cygwin, etc.

Toolchains can definitely have their own packages. CoolStar has already done that on iOS, and the unreleased Theos Cydia package depends on his toolchain. SDKs are a grey area and we need to see what's ok and what's not about that - it might be a lot easier to get away with nowadays because the SDKs don't include binaries any more, just plaintext .tbd files containing symbol names.

**Comment by rpetrich** [comment]
I'm not comfortable with distributing theos via package managers, especially with the current approach to API and build output stability. Those of us that are close to the project have enough familiarity with theos to fix our builds when newer versions do break them, but we can't expect most of our users to do so. Maybe this should be a jumping off point to define what is considered stable and public and what isn't?

**Comment by alucard0134** [comment]
@rpetrich Development repo and stable repo is a possibility

**Comment by kirb** [comment]
That's already how it works. If it works, it goes on master. If needs more
work/is experimental, it gets a branch. (There are `simctl` and `strict`
branches back on kirb/theos that aren't yet brought over to this repo.)

On Sun, 14 Feb 2016 at 03:49, alucard0134 <notifications@github.com> wrote:

> @rpetrich <https://github.com/rpetrich> Development repo and stable repo
> is a possibility
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/theos/theos/issues/111#issuecomment-183706038>.
>
-- 
Adam Demasi
HASHBANG Productions
hbang.com.au

**Comment by alucard0134** [comment]
Well here is what I propose at the least. Every couple or so commits with minor revisions an update will be sent out, major commits will result in an automatic update. @kirb Do you mean as in homebrew will want a new version after each commit also?

**Comment by ahyattdev** [comment]
The current update and model of using "make update-theos" would go against packaging under this.

**Comment by kirb** [comment]
I’ve revisited this and am trialing deploying Theos as [an npm package](https://www.npmjs.com/package/theos), which necessitates giving Theos a versioning system (semver). npm might seem like an odd choice considering there’s no JavaScript to be seen in this project, but npm is the best cross-platform package manager and directory I know of, and certainly can host any project in need of a cross-platform solution for installation, updates, dependencies, etc. Releases will be made by tagging on the repo, then continuous integration (Travis) will publish it to npm.

This may end up being our solution for all platforms but iOS going forward. Since iOS is fairly different, people expect packages to be found in Cydia, and also because the latest version of node in Cydia is 0.6 from 2011 (!), it will also be continuously deployed to a Cydia repo (whether BigBoss, ModMyi, HASHBANG, or a new one is TBD).

I’m not certain about further complicating the deploy process by adding support for more package managers, for instance a Launchpad PPA for Ubuntu and Debian; Homebrew for macOS; AUR for Arch, etc, etc. This is a lot of why I didn’t want to move away from using Git as a deployment strategy — Git is on every (reasonable) developer’s computer whether they like it or not, but Linux distros are quite divided by the package manager they believe in. It can be done, but it just adds complication I’d rather not have. The Cydia repo is already a complication considering continuous deployment from Travis to npm is just a matter of pasting an npm API key in .travis.yml.

This partly “fixes” this issue, but I’m leaving it open for now since there’s still some decisions to be made. (Will we continue to support installation via Git? Should I have versioned it as 0.x.x instead of 2.0.0? Is requiring people to install a language runtime they may never use for anything but npm silly?)

**Comment by kirb** [comment]
I think this is good to close. Just tagging releases at all solved most of the problem; if you want “stable”/“known-good” you can just checkout a tagged commit. npm releases gave another installation option, plus dm.pl is available in Cydia on repo.chariz.io. Don’t think anything more is necessary. If a distro wants to package Theos, it can be done based on our npm releases.
