### ISSUE TITLE
Question what does this mean?  https://twitter.com/saurik/status/714188263787868160

### ISSUE THREAD

**Issue by Packetfahrer** [theos/theos#149]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by uroboro** [comment]
It means that there's a small set of classes within SpringBoard that when an Objective-C runtime function is used with them an unknown side effect causes an unexpected initialization that results in this bug.

**Comment by Packetfahrer** [comment]
will this be fixed ?

**Comment by angelXwind** [comment]
I've already fixed it in commit [`c6fbe71fa4a49b4a2695c5449faea4c947cbf56a`](https://github.com/theos/theos/commit/c6fbe71fa4a49b4a2695c5449faea4c947cbf56a).

**Comment by Packetfahrer** [comment]
Okay ;)

**Comment by DHowett** [comment]
You're supposed to use the template and not treat the issue section as a discussion forum.

**Comment by kirb** [comment]
Since this has gotten quite a bit of attention and because a few have asked, here is an explanation of what went wrong here:

I realised that Logos’ internal generator doesn’t warn if there is a hook that uses a class or selector that doesn’t exist. This can happen due to a typo, or because the binary that contains that code had an update since the tweak’s release, changing the class or method name (or removing it).

In c4a136d, I implemented those messages in Logos. It checked the result of `class_getInstanceMethod()`, which returns the `Method` that’s later used to create the hook. If the value is null, then the method doesn’t exist. Same for the class. Pretty simple.

While Substrate has its own checks and logs for null classes/methods, it’s impossible for it to know the name of the class because all it has is null. Hence, it logs “nil class argument”. In the hopes of it being helpful, I also implemented the same in the Substrate generator. Considering that `class_getInstanceMethod()` is used by the internal generator, I couldn’t imagine a problem with this.

Yesterday, Karen (angelXwind) had a report of her tweak Mikoto causing the infamous “quarter screen bug” for iOS 6 users. That is, the first time SpringBoard starts after the device boots, the screen is displayed at half of the actual size of the display. The well-known cause is that a tweak has caused `-[UIDevice init]` to be called before UIDevice has been properly initialised. Problem being, the culprit wasn’t directly in her code. She had this:

```logos
%hook SBApplication

- (id)initWithApplicationInfo:(id)applicationInfo bundle:(NSBundle *)bundle infoDictionary:(NSDictionary *)dictionary {
    return %orig(applicationInfo, bundle, dictionary);
}

%end
```

If it was there, it caused the bug, even though it was only hooking a method and returning the value from the original implementation.

It turns out that there was more going on than expected – `class_getInstanceMethod()` was causing the class to be initialised. This calls `+[SBApplication initialize]`. On iOS 6.0/6.1, this method calls `+[SBPlatformController sharedInstance]`. As a shared instance of SBPlatformController doesn’t exist yet, one is initialised. The init method calls `-[SBPlatformController discoverCurrentConfiguration]`, which indeed refers to `UIDevice` a few times.

The solution was to just remove this check and let Substrate handle it, as its own log message does contain the class and selector names. Karen did this in c6fbe71. This still doesn’t fix the internal generator though, which we are considering a solution to. More than likely we will sync up with rpetrich’s Theos branch, which includes this commit: rpetrich/theos@bf4900d.
