### ISSUE TITLE
layout/ is not used in submodules

### ISSUE THREAD

**Issue by mtshare** [theos/theos#198]
## What are the steps to reproduce this issue?
1. Create a tweak using the default template (iphone/tweak)
2. Inside the tweak create a Daemon using the default template (iphone/xpc_service)
3. Create the package to install on device (make package)
## What happens?

Now if you unzip the .deb file created, you can see that the .plist file of the Daemon is missing in /Library/LaunchDaemons.
Every resources you add to the Daemon inside the layout folder were not included in the .deb.
## What were you expecting to happen?

Find all resources inside the .deb
## Any logs, error output, etc?

NO
## Any other comments?

NO
## What versions of software are you using?

**Operating System:** …
OSX 10.11.6
Xcode 7.3.1

**SDK Version:** …
9.2

**Comment by uroboro** [comment]
I haven't checked the source, but the root `layout` directory is the only one contemplated by Theos. This template has its own so it creates it in the subproject directory which is completely ignored.

I would guess that this issue didn't pop up earlier because the rest of the templates, mostly `tweak` and `preferenceloader`, use a local file that is moved by a rule in the subproject's Makefile to the staging directory. A solution could involve managing these files in the same way.

**Comment by r-plus** [comment]
I noticed this issue too.
I found this issue happen since eb8ad7e commit.
If I revert this commit, subproject's layout directory correctly deployed to staging directory.

I think this issue should fix.
