### ISSUE TITLE
Mac users with coreutils from brew can't package due to `du` not taking the same args

### ISSUE THREAD

**Issue by uroboro** [theos/theos#230]
What are the steps to reproduce this issue?
-------------------------------------------
1. Make project
2. `make package`

What happens?
-------------
Package is not built.

What were you expecting to happen?
----------------------------------
Package being built.

Any logs, error output, etc?
----------------------------
```> Making all for tweak Test…
make[2]: Nothing to be done for `internal-library-compile'.
> Making stage for tweak Test…
du: invalid option -- 'I'
Try 'du --help' for more information.
dpkg-deb: error: parsing file '/Users/username/Desktop/test/.theos/_/DEBIAN/control' near line 9 package 'com.my.testtweak:iphoneos-arm':
end of file before value of field 'Installed-Size' (missing final newline)
make: *** [internal-package] Error 2
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** macOS

**Toolchain Version:** N/A

**SDK Version:** N/A

**Comment by uroboro** [comment]
Given that we already depend on dpkg and ldid on this platform, we could potentially depend on coreutils as well if we can't distinguish which `du` is going to be used.

Relevant makefile: https://github.com/theos/theos/blob/master/makefiles/platform/Darwin.mk#L16

**Comment by DHowett** [comment]
It is invalid for a package to replace BSD du on a platform that offers BSD du with GNU du and call it BSD du, which is what brew is doing.

Both Fink and Macports namespace the GNU coreutils properly.

Perhaps an issue should be filed on Homebrew?

**Comment by uroboro** [comment]
@kirb commented that it might have been an issue on how it was installed, using `--with-default-names` which would remove the `g` prefix.

**Comment by kirb** [comment]
Homebrew *does* prefix coreutils with `g` as the others do, but it also [provides a feature](https://github.com/Homebrew/homebrew-core/blob/f3b06a6/Formula/coreutils.rb#L66-L80) to enable using them without a prefix. (Actually, there’s no `--with-default-names` for coreutils as @uroboro said I said; some other dupe formulae have that though.)

That said, we do [prefer `gdu`](https://github.com/theos/theos/blob/84c386e/makefiles/platform/Darwin.mk#L16-L22) over `du`, and `gdu` should definitely still be in the path unless the user has done a `brew unlink coreutils` or something else strange. This issue was sprouted from [this thread](https://www.reddit.com/r/jailbreakdevelopers/comments/5sld2s/help_dpkgdeb_error_parsing_file/); I’m not confident the poster is aware of what they’ve done to cause it.

I don’t think we should consider this a bug. People should be well aware that various things will break when assumptions about the environment are changed.
