### ISSUE TITLE
Move Logos and NIC to separate Git repos

### ISSUE THREAD

**Issue by kirb** [theos/theos#247]
Logos and NIC are projects that are part of Theos, but could be broken out into their own Git repos to be more tidy. I’m thinking that they should be included into the main Theos repo by creating submodules under vendor/ for each, and then creating symlinks for their executables in bin/.

DHowett already had a [separate Logos repo](https://github.com/DHowett/logos), but this is obviously a ~cherrypick~ filter-branch of commits from Theos.

dm.pl will likely also become a submodule under vendor/.

**Comment by DHowett** [comment]
It'd be pretty cool if we could keep the full history of Logos! That's why the original attempt at splitting it out was a `git filter-branch`. The frustrating part is that Logos moved around at some point in its life, and `filter-branch`'s basic file inclusion rules don't account for moves and renames.

**Comment by kirb** [comment]
Done. NIC needs some work to more carefully determine the Theos directory but it works for now if invoked via the $THEOS/bin/nic.pl symlink.
