### ISSUE TITLE
Can we hook swift functions now?

### ISSUE THREAD

**Issue by liuxuan30** [theos/theos#264]
Hi there,

After a long time, I want to ask if we can hook swift functions now?

I think I am able to get the correct class name in swift (proved by `objc_getCalss()`) but when trying to hook the functions, as simple as `-(void)[instance initialize]`, it seems not working

**Comment by kirb** [comment]
Swift methods are harder to hook due to Swift’s static nature. The generated ObjC bridge class should work for classes that inherit from NSObject, but only if the method is called from ObjC or C code (as `-[NSObject initialize]` is).

Not sure what’s going on in your situation. Are you getting a “nil class” or “message not found” log in the ASL syslog (`ondeviceconsole`) from Substrate? Maybe the class doesn’t inherit from NSObject? Directly hooking the C-style function by name (if the binary isn’t stripped) may also be possible, which would cover calls from both ObjC and Swift.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).

**Comment by liuxuan30** [comment]
Thank you for your reply. I have a test app that's written in swift, Xcode generates its objc header, so I use the header information, like class name, function name to hook as usual, however, it seems not triggered at all. At first I think it might be wrong class name, as swift has name mangling. But I test the class name using `objc_getClass()` and it returns the correct class, that's why I posted here to ask if anything special to hook

**Comment by kirb** [comment]
For code you can control, `@objc` on the class will ensure you get a full ObjC bridge class, or `@objc` on specific properties/functions to generate ObjC bridge methods only for them. Of course, that's not possible when hooking someone else's code. I don't otherwise have a good answer right now, we haven't really looked into it enough and generally seems there isn't enough interest about it.

**Comment by liuxuan30** [comment]
I came across https://www.securify.nl/blog/SFY20150302/hooking-swift-methods-for-fun-and-profit.html. Sounds like it's doable anyway?
