### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by GodlyOne123** [theos/theos#288]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Compile to a deb file

What happens?
-------------
Error during compiling 

What were you expecting to happen?
----------------------------------
Successful compiling to get deb file

Any logs, error output, etc?
----------------------------

< built-in >:1:10: error: non-portable path to file
      '"/uUsershHTDDDesktopttheosPPrefix.pch"'; specified path differs in case
      from file name on disk [-Werror,-Wnonportable-include-path]
#include "/users/htd/Desktop/theos/Prefix.pch"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         "/uUsershHTDDDesktopttheosPPrefix.pch"
1 error generated.
make[3]: *** [/users/htd/pvz2/.theos/obj/debug/armv7/Tweak.xm.fce13921.o] Error 1
make[2]: *** [/users/htd/pvz2/.theos/obj/debug/armv7/PvZ2.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [PvZ2.all.tweak.variables] Error 2

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …
iMac version 10.12.6  (27 inch late 2013)

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
You’ve manually entered the full path in lowercase (e.g. `cd /users/kirb/desktop` instead of `cd /Users/kirb/Desktop` or even `cd ~/Desktop`) and/or you’ve set `$THEOS` to an all-lowercase path. Unix OSes like macOS are designed mainly for case sensitivity, even if the filesystem is case insensitive.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
