### ISSUE TITLE
Don't response when Making stage for application

### ISSUE THREAD

**Issue by iThanh** [theos/theos#309]
**What are the steps to reproduce this issue?**
1. Using NIC to create application (select 2)
2. make package

**What happens?**
All processes are normal, but When Making stage for application AppName, It still runs, but for a long time no response and no results.

**What were you expecting to happen?**
I want to build a package

**Any logs, error output, etc?**
No log and no error.

**Any other comments?**

**What versions of software are you using?**
_Operating System:_ macOS 10.13.4
_Toolchain Version:_ lastest
_SDK Version:_ iOS 11

**Comment by iThanh** [comment]
https://ghostbin.com/paste/53rg2

Help me, please!

**Comment by ipadkid358** [comment]
Are you comfortable sharing the project? We haven't been able to reproduce the issue

**Comment by kirb** [comment]
Closing due to lack of response. If you’re still having this issue, please reopen the issue with a link to a copy of your project as @ipadkid358 suggested, or (preferred) try to create a new project that only contains as little as necessary to trigger this freeze, and upload that. Make sure you have the latest version of Theos first by running `make update-theos`.

**Comment by AtomicArticFox** [comment]
Hi i have the same problem
When i try to compile the project, theos get stuck in “Making stage for application”
