### ISSUE TITLE
make: *** [internal-install] Error 1

### ISSUE THREAD

**Issue by Insfgg99x** [theos/theos#402]
![image](https://user-images.githubusercontent.com/12442442/56346620-22308e00-61f5-11e9-8bca-6654c5848e38.png)

I got this error:
make: *** [internal-install] Error 1

**Comment by kirb** [comment]
Install Substrate.

**Comment by Insfgg99x** [comment]
Cydia Substrate?
@kirb

**Comment by kirb** [comment]
Please read the message - dpkg isn't able to fully install your package because a dependency is missing. The name is listed (mobilesubstrate). dpkg can only install/uninstall debs passed to it, so you need to take care of any missing dependencies. A quick google of "mobilesubstrate" or searching for that name in Cydia will show that it's Cydia Substrate. You can also just perform any install/uninstall/reinstall operation in Cydia and it'll pick up on any missing dependencies that need to be resolved.

**Comment by justdie386** [comment]
Yo just sayin but we can see the ip in the screenshot :skull: might wanna idk fix dat just in case y'know

**Comment by crifan** [comment]
Solution:
in `Cydia` search `Substrate`, can found `Cydia Substrate`:
![cydia_substrate](https://github.com/user-attachments/assets/621039ea-441d-4bf0-90d8-1dec98ac71e6)

 install it. done
