### ISSUE TITLE
Not support arm64e

### ISSUE THREAD

**Issue by ghost** [theos/theos#405]
Please add support for arm64e, or else developers can't update their tweaks for the newest iPhones and iPads!

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by kirb** [comment]
The latest commit 5f49e76 made arm64e a default arch when building on macOS with iOS SDK 12.2 or newer. We’re working on releasing a 12.2 patched SDK for those needing private frameworks. Building on other platforms isn’t yet supported because Apple need to release all of the updated source to LLVM and possibly other parts of the toolchain first.
