### ISSUE TITLE
killed：9

### ISSUE THREAD

**Issue by ccsx123** [theos/theos#414]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. …/var/theos/bin/nic.pl
2. …Killed:9
3. …

What happens?
-------------
…Killed:9

What were you expecting to happen?
----------------------------------
…To solve

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)
mushimushiagesen:~ root# /var/theos/bin/nic.pl
Killed: 9
mushimushiagesen:~ root#

Any other comments?
-------------------
…
no
What versions of software are you using?
----------------------------------------
**Operating System:** …ios9.3`2

**Toolchain Version:** …ios toolchain 6.1-1

**SDK Version:** …installtheos3's SDK

**Comment by uroboro** [comment]
A couple things:

- Do **not** use Theos as root. Just use `mobile` on iOS.
- Use the [official instructions](https://github.com/theos/theos/wiki/Installation-iOS) to setup Theos on your device.
- Use `/var/mobile/theos` as `THEOS` instead of the root-owned `/var/theos`.

It appears that the `perl` you installed doesn't work. Where did you get it from?

**Comment by ccsx123** [comment]
> 几件事：
> 
> * 千万**不能**使用西奥斯为根。只需`mobile`在iOS上使用。
> * 使用[官方说明](https://github.com/theos/theos/wiki/Installation-iOS)在您的设备上设置Theos。
> * 使用`/var/mobile/theos`的`THEOS`，而不是超级用户拥有`/var/theos`。
> 
> 看来`perl`你安装的不起作用。你是从哪里得到的？

cydia    
Studied a night, can help me?

**Comment by kirb** [comment]
I think this is the same issue as #460.
