### ISSUE TITLE
get ld warning about ld linking after upgrade to Xcode 11

### ISSUE THREAD

**Issue by liuxuan30** [theos/theos#446]
get ld warning about ld linking after upgrade to Xcode 11
>ld: warning: building for iOS, but linking in .tbd file (/development/mytweak/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd) built for iOS Simulator

```
==> Compiling mytweak/mytweak.m (armv7s)…
==> Linking tweak mytweak (armv7s)…
ld: warning: building for iOS, but linking in .tbd file (/development/mytweak/theos/vendor/lib/CydiaSubstrate.framework/CydiaSubstrate.tbd) built for iOS Simulator
==> Generating debug symbols for mytweak…
rm .theos/obj/debug/armv7s/Tweak.xm.mm
==> Preprocessing Tweak.xm…
==> Compiling Tweak.xm (arm64)…
```

not sure who should ask for help? It seems `CydiaSubstrate.tbd` needs an update, but this could be tricky as I don't know who can update it now. I remember saurik has left.

**Comment by kirb** [comment]
That copy of CydiaSubstrate.framework is maintained by us, and used as the generic API regardless of the hooking framework (e.g. Substitute) nowadays.

It’s not an actual issue, just a silly warning. It still generates the LC_LOAD_DYLIB command for /Library/Frameworks/CydiaSubstrate.framework/CydiaSubstrate. Not sure why it assumes it must be a simulator binary… because we have `i386, x86_64` listed in the archs? Makes no sense because we also list `armv7, armv7s, arm64` there; listed before the Intel archs even.

**Comment by melvin7** [comment]
In my project , it comes as an error

`clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

**Comment by liuxuan30** [comment]
@kirb so this is a warning from ld? I suppose this ld is coming from Xcode11. Shall we use another version or just ignore the warning

**Comment by kabiroberai** [comment]
Closing this in favor of #456
