### ISSUE TITLE
HBLogDebug stopped working

### ISSUE THREAD

**Issue by merdok** [theos/theos#461]
Hi,

after a long absence I did update theos and my SDK to 11.2 recently to do some iOS13 updates and i noticed that **HBLogDebug** did stop working for me. 
Basically nothing gets logged anymore in the Console.app when i use this. When i use **NSLog** then the logging works fine.
Any idea what the issue is here?

**Comment by mtshare** [comment]
Same for me

**Comment by kirb** [comment]
You may need to enable display of verbose/debug logs in the menus of Console.app. Does that fix the issue?

Maybe we should change it to use the info level rather than debug, so it doesn’t get filtered out. The idea is that you could use HBLogDebug() to log lots of data very often, with near-zero performance penalty even in production code unless Console.app is open - but I don’t think anyone has ever done that. So making HBLogDebug() equivalent to HBLogInfo() is probably fine. HBLogDebug() would still differ in that it’ll compile to nothing for release builds, so HBLogInfo() still has a purpose as a log function that remains in release builds.

**Comment by mtshare** [comment]
@kirb Thank you for the quick reply! Enabling Actions → Include Debug Messages in Console.app works fine! Can't see **HBLogInfo** anyway.

I'm on Catalina with latest Xcode version.

**Comment by merdok** [comment]
Working for also when enabled "Include Debug Messages"

**Comment by 3xtc** [comment]
I’m noob but have same problem how& where do I enable actions include debug messages

**Comment by 3xtc** [comment]
> @kirb Thank you for the quick reply! Enabling Actions → Include Debug Messages in Console.app works fine!
> 
> Is there any way to see logs using Socket CAT on device (over SSH)?

Please help me fix I have same problem
