### ISSUE TITLE
Theos won't make package since fresh Mac OS reinstall

### ISSUE THREAD

**Issue by aesthyrica** [theos/theos#470]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. … reinstalled clean Mac OS Mojave
2. … install Xcode then after home-brew
3. …install dependencies then Theos
4. …create tweak and then cd into folder
5. …Run command "make package"

What happens?
-------------
chloees-MacBook-Pro:sposify chloee$ make
Makefile:3: /makefiles/common.mk: No such file or directory
Makefile:10: /tweak.mk: No such file or directory
make: *** No rule to make target `/tweak.mk'.  Stop.

What were you expecting to happen?
It to work like it used too

What versions of software are you using?
Mojave latest and Xcode 11.3
**Operating System:** …
10.14.6 Mojave

**Comment by kirb** [comment]
Did you miss step 2 [here](https://github.com/theos/theos/wiki/Installation-macOS) by any chance? You need to restart your shell after running that. If you run `echo $THEOS`, do you get back what you set in step 2?

I updated it as I realised it’s missing instructions for a macOS 10.15 change (the default shell changed from bash to zsh), but as you’re on Mojave you should use `~/.profile` instead of `~/.zshrc`.

**Comment by aesthyrica** [comment]
I did step 2 but let me just retry everything you've just said me and ill get back to you on here in little while when my Mac isn't on 3%, also thanks so much for a quick response.
