### ISSUE TITLE
Hooks in Swift 

### ISSUE THREAD

**Issue by anynon** [theos/theos#504]
Hi, is there any way to hook stuff, and make a tweak entirely in swift with no objective C. 

I've been [playing around with AutoHook](https://github.com/level3tjg/AutoHook-Swift) but it's super slow and causes performance issues even when you only have one or two hooks.

**Comment by kabiroberai** [comment]
While I generally avoid talking about future projects, I can say that I’m working on a Logos-style hooking system which can be used in Swift (although it’ll still only be for hooking ObjC methods, not pure Swift stuff). If/when that happens, we’ll probably make it the “official” solution which can be used out of the box with Theos.

**Comment by AT5Hack** [comment]
> While I generally avoid talking about future projects, I can say that I’m working on a Logos-style hooking system which can be used in Swift (although it’ll still only be for hooking ObjC methods, not pure Swift stuff). If/when that happens, we’ll probably make it the “official” solution which can be used out of the box with Theos.

is it possible to hook swift functions that have arguments or is that considered "pure swift"? I'm able to hook normal swift functions but if it has an argument I get "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[KillerClownCall.ViewController callUserBackWithDelay:]: unrecognized selector sent to instance 0x101a0e590'"

 Sorry its hard for me to find any information on this.
