### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by iplovings** [theos/theos#548]
![image](https://user-images.githubusercontent.com/64208426/97066024-8eb4e780-1566-11eb-920b-7fd6c51a27d2.png) pls help me guys, I am using latest version of everything and u can see my sdk version in the ss

**Comment by kirb** [comment]
You extracted a template directly rather than using NIC. You need to copy the `.nic.tar` into `$THEOS/templates/`, then run `$THEOS/bin/nic.pl` to generate a project.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
