### ISSUE TITLE
Compiling SwiftUI app with Theos

### ISSUE THREAD

**Issue by thelazyitguy** [theos/theos#585]
![Screen Shot 2021-03-22 at 12 01 34 PM](https://user-images.githubusercontent.com/60739640/112020284-97561d80-8b06-11eb-8be8-0cc7578ac1f9.png)

**Operating System:** macOS M1

**Toolchain Version:** xcode11

**Comment by RPwnage** [comment]
This is a source code specific error message. It’s about the code you’re trying to compile and not an issue of Theos.

**Comment by thelazyitguy** [comment]
If so, could you tell me what you think the issue is? app works fine.

**Comment by RPwnage** [comment]
It seems to be initializing the ElixirApp struct multiple times. The weird thing is that this is the same file/definition, but I can't tell you any more about this, I'm not experienced in Swift at all.

**Comment by kirb** [comment]
What is in your makefile? Are you using `$(wildcard …)` by any chance? It somewhat looks like you have both `ElixirApp.swift` and `./ElixirApp.swift` specified, which isn’t getting deduplicated because the paths are different in a strict string comparison.

Can you try `make clean all messages=yes` and [ghostbin](https://ghostbin.co) the output?

**Comment by Memoasiri1877** [comment]
> ![Screen Shot 2021-03-22 at 12 01 34 PM](https://user-images.githubusercontent.com/60739640/112020284-97561d80-8b06-11eb-8be8-0cc7578ac1f9.png)
> 
> **Operating System:** macOS M1
> 
> **Toolchain Version:** xcode11

**Comment by chrisharper22** [comment]
This specific case has been solved, so it can be marked as closed.
