### ISSUE TITLE
Missing blank line at end of control causes error: '.theos/_/DEBIAN/control' is missing a Version field

### ISSUE THREAD

**Issue by yur1xpp** [theos/theos#601]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Install latest theos
2. run `make package install`

What happens?
-------------
theos will throw "'.theos/_/DEBIAN/control' is missing a Version field" error during installation to device

What were you expecting to happen?
----------------------------------
Install normally

Any logs, error output, etc?
----------------------------
This is the control file at .theos/_/DEBIAN/control
```
Package: com.my.package
Name: MyPackage
Depends: mobilesubstrate, preferenceloader, com.rpetrich.rocketbootstrap (>= 1.0.2), firmware(>=13.0), com.spark.libsparkcolourpicker
Architecture: iphoneos-arm
Description: My description
Maintainer: me
Author: me
Section: Tweaks
Conflicts: com.my.conflict
Icon: https://url/icon.png
Depiction: https:my/urlVersion: 1.2.3
Installed-Size: 1144
```

Any other comments?
-------------------
Notice that the Version: 1.2.3 is not correctly formatted in Depiction field. The original control file in root older is correctly formatted however.

What versions of software are you using?
----------------------------------------
**Operating System:** big sur

**Toolchain Version:** Xcode 11

**SDK Version:** 14.4

**Comment by kirb** [comment]
Is the `control` in your project missing a final blank line at the end of the file, or is it possibly using Windows (CRLF) or Classic Mac OS (CR) line endings?

**Comment by yur1xpp** [comment]
You're right! the control file did missing a final blank line. This was never an issue before, is this new, or a bug? I just reinstalled my OS today so everything is new, including theos (I rarely update). I also noticed that now I have to manually links against a tons of Frameworks too (UIKit, CoreImage, QuartzCore etc), which before is not required.

**Comment by kirb** [comment]
I think this has been a long-term bug that hasn’t really ever been fixed, though perhaps it did get fixed at one point and later was broken again. Hard to decide whether we should or shouldn’t try to accommodate it, because by the Debian specification, a control without a final blank line is invalid and would fail to install later on anyway.

The other thing you mention is an intentional change that applies when using iOS 14 SDK or later, we’ve deprecated this implicit behavior to match the standard Xcode project config, and to avoid unintentionally linking against UIKit in situations where it may cause problems.

**Comment by kirb** [comment]
Fixed with theos/dm.pl#19
