### ISSUE TITLE
installed theos still wrong

### ISSUE THREAD

**Issue by DST2016** [theos/theos#602]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

what can I fix

<img width="920" alt="WX20210615-152711@2x" src="https://user-images.githubusercontent.com/20701337/122010940-30d35980-cdee-11eb-9b5f-155974532b8c.png">

<img width="1400" alt="WX20210615-152628@2x" src="https://user-images.githubusercontent.com/20701337/122010836-126d5e00-cdee-11eb-9029-009c90895f82.png">

What are the steps to reproduce this issue?
-------------------------------------------
1. …
2. …
3. …

What happens?
-------------
…

What were you expecting to happen?
----------------------------------
…

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** …

**Toolchain Version:** …

**SDK Version:** …

**Comment by kirb** [comment]
It seems like you’re using an Xcode build script which was not developed by us, so you likely should be contacting the developer of that script, rather than the Theos project.

Closing as this is not a Theos issue. If you need further assistance, take a look at our [help page](https://github.com/theos/theos/wiki/Help).
