### ISSUE TITLE
Swift files that don't depend on each other don't seem to get cached in an app project during compilation

### ISSUE THREAD

**Issue by Luki120** [theos/theos#662]
### What are the steps to reproduce this issue?

1) Make new project
2) Add a few Swift files
3) Compile
4) Modify only one
5) Compile again

### What happens?

- All files get compiled again

### What were you expecting to happen?

- For the files that haven't been modified to get cached, like it happens when writing Objective-C

### Paste any relevant logs, error output, etc.

-

### Additional context

-

### What OS are you seeing the problem on?

Linux/WSL

### What OS version does it have installed?

Kubuntu 21.04

### What toolchain and version are you using?

Kabir's Swift 5.6.1 toolchain

### Which SDK version are you using?

iOS 15.5

### What OS is your client device running?

iOS

### What OS version does it have installed?

iOS 14.5.1

### Which device model is it?

iPod Touch 7th generation

### Which jailbreak is it using (if relevant)?

checkra1n

**Comment by kirb** [comment]
This is somewhat correct behavior, by changing one file you might be changing characteristics other files in the project depend on, e.g. function signature, the exact address to a function, etc. Swift is just going to be like this because of its lack of headers, and stronger leaning on static compile-time constants rather than runtime lookups as ObjC is. swiftc's makedeps output drives this. It's still possible that it could be somehow implemented wrong in Theos though.

**Comment by kabiroberai** [comment]
Are you on the Orion branch? We pass all swift files to the compiler invocation like @kirb mentioned, but swiftc itself should skip files that have no changes/changed dependencies, and you shouldn't see the "Compiling Foo.swift" line in Theos' output

**Comment by Luki120** [comment]
Yeah, I'm on the Orion branch. Here's a [live showcase](https://raw.githubusercontent.com/Luki120/luki120.github.io/master/assets/Misc/rip.mp4) of the behavior

**Comment by Luki120** [comment]
This might be a Swift issue rather than a Theos one, as discussed on the Discord server, so closing due to lack of more information
