### ISSUE TITLE
I try make package and i have this error

### ISSUE THREAD

**Issue by D7my2001** [theos/theos#695]
![image](https://user-images.githubusercontent.com/120202931/212341537-e06094b0-daf0-43fb-a3ef-5ee09c883a78.png)

**Comment by D7my2001** [comment]
This is the project

https://github.com/haoict/crackerxi-searchbar#building

**Comment by ExTBH** [comment]
Download `libhdev` from BigBoss
if you done with #694 mark it as closed

**Comment by D7my2001** [comment]
> Download `libhdev` from BigBoss
> 
> if you done with #694 mark it as closed

I already install it

**Comment by ExTBH** [comment]
https://github.com/haoict/libhdev-public#installation

**Comment by ExTBH** [comment]
that means
```bash
git clone https://github.com/haoict/libhdev-public.git
mv libhdev-public/libhdev.framework $THEOS/lib/
rm -rf libhdev-public
```
as mobile not root

**Comment by D7my2001** [comment]
Permission denied
![image](https://user-images.githubusercontent.com/120202931/212350839-3bce7463-b167-4a33-9d87-a1f17ce6c2fb.png)

**Comment by ExTBH** [comment]
run `ls -l $THEOS`

**Comment by D7my2001** [comment]
![image](https://user-images.githubusercontent.com/120202931/212351342-8ffb3a34-87e7-4a00-b20c-ba747177ac23.png)

**Comment by ExTBH** [comment]
this isnt supposed to happen we installed as mobile :skull: 
https://github.com/theos/theos/issues/694#issuecomment-1381847383
did you use root or mobile?

**Comment by D7my2001** [comment]
> this isnt supposed to happen we installed as mobile :skull: 
> 
> https://github.com/theos/theos/issues/694#issuecomment-1381847383
> 
> did you use root or mobile?

To be honest with you I try to install theos Like you told me but I couldn't there is no guide so i used auto Installer 😔

**Comment by ExTBH** [comment]
if you gonna go the installer way, can't help you there's a reason why all problems are from them

**Comment by D7my2001** [comment]
I solvet man thank u bro I really appreciate that (الله يجزاك خير ويعطيك العافية)

**Comment by L1ghtmann** [comment]
@D7my2001 there is a guide available at https://theos.dev/docs. Note that there are a couple items out-of-date in those docs -- one relating to the dependencies on Elucubratus-strapped devices (which you can find more information about [here](https://github.com/theos/theos/issues/559#issuecomment-744206496)) and devices using checkra1n (you'll want to install Theos to `/opt/theos/` instead of `~/theos`)). 
---
So three things:
1) login as root with `su` and then remove your Theos install (`rm -r /var/theos/`)
2) check that Theos is removed by running `ls -A $THEOS`. If this shows a "no such file or directory" error, type `exit` and then try the command again. 
3) Assuming it shows the "no such file or directory error" again, you'll want to go ahead and install Theos by following the docs mentioned above, being sure to note the two caveats I listed.

**Comment by xiaooojun** [comment]
> I solvet man thank u bro I really appreciate that (الله يجزاك خير ويعطيك العافية)
How to solve it? how to set up mobile users
